FROM lballabio/quantlib-swig-devenv:base
MAINTAINER Luigi Ballabio <luigi.ballabio@gmail.com>
LABEL Description="A development environment for building QuantLib-SWIG on Travis CI"

RUN cd /QuantLib \
 && ./autogen.sh \
 && ./configure --enable-unity-build --disable-static CC=clang CXX=clang++ CXXFLAGS='-O3 -g0' \
 && make -j 4 && make install \
 && cd .. && rm -rf /QuantLib

RUN ldconfig

CMD bash
