FROM lballabio/boost
MAINTAINER Luigi Ballabio <luigi.ballabio@gmail.com>
LABEL Description="A testing environment for building QuantLib and its SWIG bindings"

RUN apt-get update && apt-get install -y python-dev \
                                         ruby-dev \
                                         mono-devel \
                                         r-base-dev texlive \
                                         default-jdk

