name: Build quantlib-swig-devenv Docker images
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Checkout latest QuantLib master
      uses: actions/checkout@v2
      with:
        repository: lballabio/QuantLib
        path: quantlib-swig-devenv/QuantLib
    - name: Build Docker images
      run: |
        rm -rf quantlib-swig-devenv/QuantLib/.git
        make quantlib-swig-devenv TAG=rolling
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Push Docker images
      run: |
        docker push ghcr.io/lballabio/quantlib-swig-devenv:csharp
        docker push ghcr.io/lballabio/quantlib-swig-devenv:java
        docker push ghcr.io/lballabio/quantlib-swig-devenv:scala
        docker push ghcr.io/lballabio/quantlib-swig-devenv:r
        docker push ghcr.io/lballabio/quantlib-swig-devenv:python3
