name: Build quantlib-devenv Docker images
on: workflow_dispatch
env:
  BOOST_VERSION: 1.75.0
  ROLLING: groovy
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        tag: [focal, groovy]
    steps:
    - uses: actions/checkout@v2
    - name: Build images
      run: |
        make boost TAG=${{ matrix.tag }} BOOST_VERSION=$BOOST_VERSION
        make quantlib-devenv TAG=${{ matrix.tag }}
        docker tag ghcr.io/lballabio/quantlib-devenv:${{ matrix.tag }} ghcr.io/lballabio/quantlib-devenv:${{ matrix.tag }}-$BOOST_VERSION
        if test "${{ matrix.tag }}" = "$ROLLING" ; then
            docker tag ghcr.io/lballabio/boost:${{ matrix.tag }} ghcr.io/lballabio/boost:rolling
            docker tag ghcr.io/lballabio/quantlib-devenv:${{ matrix.tag }} ghcr.io/lballabio/quantlib-devenv:rolling
        fi
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Push Docker images
      run: |
        docker push ghcr.io/lballabio/quantlib-devenv:${{ matrix.tag }}-$BOOST_VERSION
        docker push ghcr.io/lballabio/quantlib-devenv:${{ matrix.tag }}
        if test "${{ matrix.tag }}" = "$ROLLING" ; then
            docker push ghcr.io/lballabio/boost:rolling
            docker push ghcr.io/lballabio/quantlib-devenv:rolling
        fi
