name: Build quantlib-swig-devenv Docker images
on: workflow_dispatch
jobs:
  build-base:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Checkout latest QuantLib master
      uses: actions/checkout@v3
      with:
        repository: lballabio/QuantLib
        path: quantlib-swig-devenv/QuantLib
    - name: Build Docker images
      working-directory: quantlib-swig-devenv
      run: |
        rm -rf QuantLib/.git
        docker build -f Dockerfile.base --build-arg tag=rolling -t ghcr.io/lballabio/quantlib-swig-devenv:base .
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Push Docker images
      run: |
        docker push ghcr.io/lballabio/quantlib-swig-devenv:base
  build-ql:
    runs-on: ubuntu-20.04
    needs: build-base
    strategy:
      matrix:
        tag: [default, threadsafe]
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker images
      working-directory: quantlib-swig-devenv
      run: |
        docker build -f Dockerfile.${{ matrix.tag }} -t ghcr.io/lballabio/quantlib-swig-devenv:${{ matrix.tag }} .
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Push Docker images
      run: |
        docker push ghcr.io/lballabio/quantlib-swig-devenv:${{ matrix.tag }}
  build-main-languages:
    runs-on: ubuntu-20.04
    needs: build-ql
    strategy:
      matrix:
        lang: [python3, csharp, java, r]
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker images
      working-directory: quantlib-swig-devenv
      run: |
        docker build -f Dockerfile.${{ matrix.lang }} -t ghcr.io/lballabio/quantlib-swig-devenv:${{ matrix.lang }} .
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Push Docker images
      run: |
        docker push ghcr.io/lballabio/quantlib-swig-devenv:${{ matrix.lang }}
  build-dependent-languages:
    runs-on: ubuntu-20.04
    needs: build-main-languages
    strategy:
      matrix:
        lang: [scala]
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker images
      working-directory: quantlib-swig-devenv
      run: |
        docker build -f Dockerfile.${{ matrix.lang }} -t ghcr.io/lballabio/quantlib-swig-devenv:${{ matrix.lang }} .
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Push Docker images
      run: |
        docker push ghcr.io/lballabio/quantlib-swig-devenv:${{ matrix.lang }}
